onEvent('recipes', e => {
    e.recipes.bloodmagic.array('minecraft:gunpowder', '#minecraft:coals', 'minecraft:flint').texture('bloodmagic:textures/models/alchemyarrays/spikearray.png')
    e.recipes.bloodmagic.array(Item.of('4x minecraft:feather'), 'minecraft:stick', 'minecraft:bone_meal').texture('bloodmagic:textures/models/alchemyarrays/magnetismsigil.png')
    e.recipes.bloodmagic.array('minecraft:leather', '#minecraft:coals', 'minecraft:rotten_flesh').texture('bloodmagic:textures/models/alchemyarrays/lavasigil.png')
    e.recipes.bloodmagic.array(Item.of('2x minecraft:ink_sac'), 'minecraft:leather', '#minecraft:coals').texture('bloodmagic:textures/models/alchemyarrays/bindingarray.png')
    e.recipes.bloodmagic.array('mana-and-artifice:aum', 'minecraft:poppy', 'minecraft:bone_meal').texture('bloodmagic:textures/models/alchemyarrays/voidsigil.png')
    e.recipes.bloodmagic.array('mana-and-artifice:chimerite_gem', 'minecraft:emerald', 'minecraft:diamond').texture('bloodmagic:textures/models/alchemyarrays/spikearray.png')
    e.recipes.bloodmagic.array('minecraft:snowball', 'minecraft:clay_ball', 'minecraft:quartz').texture('bloodmagic:textures/models/alchemyarrays/bindingarray.png')
    e.recipes.bloodmagic.array('minecraft:pufferfish', 'minecraft:gold_ingot', 'mysticalagriculture:water_agglomeratio').texture('bloodmagic:textures/models/alchemyarrays/watersigil.png')
    e.recipes.bloodmagic.array('minecraft:turtle_egg', 'minecraft:egg', 'mana-and-artifice:mote_water').texture('bloodmagic:textures/models/alchemyarrays/watersigil.png')
    e.recipes.bloodmagic.array(Item.of('2x minecraft:prismarine_shard'), 'minecraft:prismarine_crystals', 'minecraft:prismarine_crystals').texture('bloodmagic:textures/models/alchemyarrays/watersigil.png')
    e.recipes.bloodmagic.array('minecraft:end_portal_frame', 'minecraft:end_stone', 'minecraft:ender_eye').texture('bloodmagic:textures/models/alchemyarrays/voidsigil.png')
    e.recipes.bloodmagic.array('astralsorcery:constellation_paper', 'astralsorcery:parchment', 'astralsorcery:aquamarine').texture('bloodmagic:textures/models/alchemyarrays/moonarray.png')
    e.recipes.bloodmagic.array('turtlemancy:oyster', 'minecraft:sand', 'turtlemancy:turtle_bless').texture('bloodmagic:textures/models/alchemyarrays/watersigil.png')
    e.recipes.bloodmagic.array('minecraft:nautilus_shell', 'turtlemancy:bewitched_shell', 'mana-and-artifice:mote_water').texture('bloodmagic:textures/models/alchemyarrays/watersigil.png')
})