var bTrans = <recipetype:astralsorcery:block_transmutation>;

bTrans.addRecipe("1", <blockstate:minecraft:sand>, <blockstate:minecraft:cobblestone_slab>, false, 200);
bTrans.addRecipe("2", <blockstate:minecraft:gravel>, <blockstate:minecraft:cobblestone>, false, 200);
bTrans.addRecipe("3", <blockstate:minecraft:iron_ore>, <blockstate:eidolon:smooth_stone_tiles>, false, 400);
bTrans.addRecipe("4", <blockstate:minecraft:dirt>, <blockstate:minecraft:oak_planks>, false, 150);
bTrans.addRecipe("5", <blockstate:minecraft:diamond_ore>, <blockstate:morecharcoal:sugarcane_charcoal_block>, false, 800);
bTrans.addRecipe("6", <blockstate:minecraft:andesite>, <blockstate:minecraft:stone>, false, 400);
bTrans.addRecipe("7", <blockstate:astralsorcery:rock_crystal_ore>, <blockstate:minecraft:glass>, false, 400);
bTrans.addRecipe("8", <blockstate:minecraft:granite>, <blockstate:minecraft:andesite>, false, 400);
bTrans.addRecipe("9", <blockstate:astralsorcery:aquamarine_sand_ore>, <blockstate:minecraft:terracotta>, false, 400);
bTrans.addRecipe("10", <blockstate:minecraft:diorite>, <blockstate:minecraft:granite>, false, 400);
bTrans.addRecipe("11", <blockstate:minecraft:blackstone>, <blockstate:minecraft:nether_bricks>, false, 400);
bTrans.addRecipe("12", <blockstate:astralsorcery:marble_raw>, <blockstate:minecraft:polished_basalt>, false, 200);
bTrans.addRecipe("13", <blockstate:minecraft:water>, <blockstate:minecraft:oak_leaves>, false, 400);
bTrans.addRecipe("14", <blockstate:minecraft:sugar_cane:age=0>, <blockstate:minecraft:wheat:age=7>, true, 400);
bTrans.addRecipe("15", <blockstate:eidolon:lead_ore>, <blockstate:minecraft:chiseled_stone_bricks>, false, 400);
bTrans.addRecipe("16", <blockstate:minecraft:white_wool>, <blockstate:minecraft:grass_block>, false, 200);
bTrans.addRecipe("17", <blockstate:mana-and-artifice:vinteum_ore>, <blockstate:eidolon:smooth_stone_bricks>, false, 400);
bTrans.addRecipe("18", <blockstate:occultism:copper_ore>, <blockstate:minecraft:polished_granite>, false, 400);
bTrans.addRecipe("19", <blockstate:occultism:silver_ore>, <blockstate:minecraft:polished_diorite>, false, 400);
bTrans.addRecipe("20", <blockstate:minecraft:gold_ore>, <blockstate:minecraft:hay_block>, false, 400);
bTrans.addRecipe("21", <blockstate:occultism:candle_white>, <blockstate:eidolon:candle>, false, 400);
bTrans.addRecipe("22", <blockstate:pyromancer:cinnabar_ore>, <blockstate:minecraft:crimson_nylium>, false, 400);
bTrans.addRecipe("23", <blockstate:minecraft:cactus>, <blockstate:occultism:datura:age=7>, true, 400);
bTrans.addRecipe("24", <blockstate:occultism:iesnium_ore_natural:uncovered=false>, <blockstate:minecraft:chiseled_polished_blackstone>, true, 600);
bTrans.addRecipe("25", <blockstate:minecraft:sea_lantern>, <blockstate:minecraft:quartz_block>, false, 400);
bTrans.addRecipe("26", <blockstate:minecraft:cocoa:age=0>, <blockstate:minecraft:nether_wart>, false, 400);
bTrans.addRecipe("27", <blockstate:minecraft:bee_nest>, <blockstate:minecraft:cocoa:age=2>, true, 800);
bTrans.addRecipe("28", <blockstate:minecraft:sea_pickle:waterlogged=false>.withProperty('pickles', 2), <blockstate:occultism:candle_white>, true, 400);
bTrans.addRecipe("29", <blockstate:minecraft:seagrass>, <blockstate:minecraft:grass>, false, 400);
bTrans.addRecipe("30", <blockstate:minecraft:oak_sapling>, <blockstate:minecraft:tall_grass>, false, 200);
bTrans.addRecipe("31", <blockstate:mysticalagriculture:infusion_pedestal>, <blockstate:kubejs:star_infused_bedrock>, false, 400);
bTrans.addRecipe("32", <blockstate:minecraft:coal_ore>, <blockstate:minecraft:oak_log>, false, 400);
bTrans.addRecipe("33", <blockstate:minecraft:bamboo>, <blockstate:mysticalagriculture:inferium_crop:age=7>, true, 400);